DiplomFreelance/Controllers/ChatController.cs
using DiplomFreelance.Controllers.BusinessLogic.IService;
using DiplomFreelance.Models.FreelanceModels;
using DiplomFreelance.Models.FreelanceModels.Convertors;
using DiplomFreelance.Models.FreelanceModels.DBModel;
using DiplomFreelance.Models.FreelanceModels.DomainModel;
using DiplomFreelance.Models.FreelanceModels.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiplomFreelance.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
      
        private static IServiceChat _serviceChat;
        private static IServiceMessage _serviceMessage;

        public ChatController(IServiceChat serviceChat,
          IServiceMessage serviceMessage)
        {
            _serviceChat = serviceChat;
            _serviceMessage = serviceMessage;

        }

        //Выводит на страницу чаты авторизированного пользователя
        public ActionResult ChatPartial(string iduser)
        {
            if (!String.IsNullOrEmpty(iduser))
            {
                DomainChat chat = new DomainChat();
                if (User.IsInRole("Customer"))
                    chat = _serviceChat.GetChat(User.Identity.GetUserId(), iduser);
                else
                    chat = _serviceChat.GetChat(iduser, User.Identity.GetUserId());
                if (chat.ID == 0)
                {
                    Chat chatDb;
                    if (User.IsInRole("Customer"))
                    {
                        chatDb = new Chat()
                        {
                            ID_User_1 = User.Identity.GetUserId(),
                            ID_User_2 = iduser
                        };
                    }
                    else
                    {
                        chatDb = new Chat()
                        {
                            ID_User_1 = iduser,
                            ID_User_2 = User.Identity.GetUserId()
                        };
                    }
                    _serviceChat.CreateNewChat(chatDb);
                }
            }
            var identityID = User.Identity.GetUserId();
            var chats = _serviceChat.GetChats(identityID);
           
            return PartialView("_ChatPartial", chats.ConvertToChatViewModel());

        }

        //выводи диалоги к выбранному чату
        public ActionResult DialogPartial(int? idChat)
        {
            if (idChat != null)
            {
                List<MessageViewModel> mvm = _serviceMessage.GetMessagesByChatId((int)idChat).ConvertToMessageViewModel();
                MessageDialogViewModel msg = new MessageDialogViewModel
                {
                   messages = mvm,
                   ID_Chat = (int)idChat
                };
                return PartialView("_DialogPartial", msg);
            }
            else
            {
                return PartialView("_DialogPartial", null);
            }
        }

       //выводит сообщения к определенному чату
        public ActionResult MessageBoxPartial(int? idChat)
        {
                List<MessageViewModel> mvm = _serviceMessage.GetMessagesByChatId((int)idChat).ConvertToMessageViewModel();
                MessageDialogViewModel msg = new MessageDialogViewModel
                {
                    messages = mvm,
                    ID_Chat = (int)idChat
                };
                return PartialView("_MessageBoxPartial", msg);
        }

        //служит для отправки сообщения
        [HttpPost]
        public ActionResult SendMessage(CreateMessageViewModel model)
        {

            model.Sender = User.Identity.GetUserId();
            TimeZoneInfo moscowTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time");
            string moscowTime = (DateTime.UtcNow + moscowTimeZone.BaseUtcOffset).ToString("yyyy-MM-dd HH:mm");
            model.Time_send = Convert.ToDateTime(moscowTime);
            _serviceMessage.CreateNewMessage(model);
            return RedirectToAction("MessageBoxPartial", new { idChat = model.ID_Chat });

        }
    }
}

DiplomFreelance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>33lance - Дипломный проект</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="module" src="~/Scripts/orderScripts.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--Шрифты-->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@445&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">

    <!--lightbox для изображений-->
    <link href="~/Content/lightbox.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm p-3">

        <button class="navbar-toggler border-0 row" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span><i class="fa fa-bars fa-2x" aria-hidden="true"></i></span><h2 class="text-muted ml-2">Меню</h2>
        </button>


        <div class="collapse navbar-collapse " id="navbarNavDropdown">

            <ul class="navbar-nav mr-auto font-weight-bold" id="nav-items">
                @if (User.IsInRole("Executor"))
                {
                    <li class="nav-item">
                        @Html.ActionLink("Заказы", "OrderForExecutor", "Executor", new { area = "" }, new { @class = "nav-link text-black-50" })
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        @Html.ActionLink("Создать заказ", "Order", "Customer", new { area = "" }, new { @class = "nav-link text-black-50" })
                    </li>
                }
                <li class="nav-item">
                    @Html.ActionLink("Каталог", "Catalog", "Global", new { area = "" }, new { @class = "nav-link text-black-50" })
                </li>
                @if (User.IsInRole("Executor"))
                {
                    <li class="nav-item">
                        @Html.ActionLink("Настройки", "ChangeExecutorProfile", "Manage", new { area = "" }, new { @class = "nav-link text-black-50" })
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        @Html.ActionLink("Мои заказы", "MyOrders", "Customer", new { area = "" }, new { @class = "nav-link text-black-50" })
                    </li>
                }
                <li class="nav-item">
                    @Html.ActionLink("Поддержка", "Support", "Global", new { area = "" }, new { @class = "nav-link text-black-50" })
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link text-black-50" href="#" data-toggle="modal" data-target="#chatModalCenter">Чат</a>
                    </li>
                }

                @*<li class="nav-item pl-lg-2">
                        @using (Html.BeginForm("Services", "Global", FormMethod.Post, new { @class = "form-inline", role = "form" }))
                        {
                            <div class="input-group">
                                <input type="text" class="form-control" name="nameService" placeholder="Поиск услуги" aria-label="Search" aria-describedby="basic-addon1">
                                <div class="input-group-append">
                                    <button class="btn bttn btn-outline-success rounded" type="submit" id="basic-addon1"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </div>
                            </div>
                        }
                    </li>*@
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container-fluid body-content">
        <div id="mainBody" style="min-height: 80vh">
            @RenderBody()

            @if (User.Identity.IsAuthenticated)
            {
                <!-- Modal Chat-->
                <div class="modal fade bd-example-modal-lg" id="chatModalCenter" tabindex="-1" role="dialog" aria-labelledby="chatModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-lg modal-dialog-centered " role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Чат</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body p-0" style="height: 50vh; max-height: 50vh; width:auto;" id="chatBody">
                                @{ Html.RenderAction("ChatPartial", "Chat"); }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>


    </div>
    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Free<span>lance</span></h3>

            <p class="footer-links text-dark">
                <a href="@Url.Action("Catalog","Global")">Каталог</a>
                ·
                <a href="@Url.Action("Support","Global")">Поддержка</a>
                ·
                <a href="#" data-toggle="modal" data-target="#chatModalCenter">Чат</a>
            </p>

            <p class="footer-company-name text-dark">33lance © 2020</p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>5 Улица Пионерская</span> Коломна, Россия</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+7 967 287 89 88</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:your.hat3@gmail.com">support@gmail.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>О нас</span>
                Наша площадка была разработана в качестве дипломного проекта, целью которого является разработка абсолютно бесплатной среды фриланса. Тыкай, публикуй, исполняй!
            </p>

            <div class="footer-icons">

                <a href="https://vk.com/hat33"><i class="fa fa-vk" aria-hidden="true"></i></a>      
                <a href="https://www.instagram.com/ddsdf041/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="https://github.com/ddsdf041/-"><i class="fa fa-github"></i></a>

            </div>

        </div>

    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/lightbox.js"></script>
    @*  <script src="~/Scripts/lightbox-plus-jquery.js"></script>*@
</body>
</html>